/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

// #include "src/proto/cmd.pb.h"
#include "cmd.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cmd_RequestLockStateUpdate, cmd_RequestLockStateUpdate, AUTO)


PB_BIND(cmd_RequestLockStateGet, cmd_RequestLockStateGet, AUTO)


PB_BIND(cmd_Request, cmd_Request, AUTO)


PB_BIND(cmd_ConfirmLockStateUpdate, cmd_ConfirmLockStateUpdate, AUTO)


PB_BIND(cmd_ConfirmLockStateGet, cmd_ConfirmLockStateGet, AUTO)


PB_BIND(cmd_Confirm, cmd_Confirm, AUTO)




