/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_CMD_SRC_PROTO_CMD_PB_H_INCLUDED
#define PB_CMD_SRC_PROTO_CMD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _cmd_State {
    cmd_State_STATE_UNKNOWN = 0,
    cmd_State_UNLOCKED = 1,
    cmd_State_LOCKED_PRIVACY = 2,
    cmd_State_LOCKED_DEADLOCK = 3,
    cmd_State_ERROR_FORCED = 4,
    cmd_State_ERROR_JAMMED = 5
} cmd_State;

/* Struct definitions */
typedef struct _cmd_RequestLockStateUpdate {
    bool has_desiredState;
    cmd_State desiredState;
    bool has_desiredStateToken;
    uint64_t desiredStateToken;
} cmd_RequestLockStateUpdate;

typedef struct _cmd_RequestLockStateGet {
    bool has_request;
    cmd_RequestLockStateUpdate request;
} cmd_RequestLockStateGet;

typedef struct _cmd_Request {
    bool has_lockStateUpdate;
    cmd_RequestLockStateGet lockStateUpdate;
} cmd_Request;

typedef struct _cmd_ConfirmLockStateUpdate {
    bool has_desiredState;
    cmd_State desiredState;
    bool has_reportedState;
    cmd_State reportedState;
    bool has_desiredStateToken;
    uint64_t desiredStateToken;
} cmd_ConfirmLockStateUpdate;

typedef struct _cmd_ConfirmLockStateGet {
    bool has_confirm;
    cmd_ConfirmLockStateUpdate confirm;
} cmd_ConfirmLockStateGet;

typedef struct _cmd_Confirm {
    bool has_lockStateConfirm;
    cmd_ConfirmLockStateGet lockStateConfirm;
} cmd_Confirm;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _cmd_State_MIN cmd_State_STATE_UNKNOWN
#define _cmd_State_MAX cmd_State_ERROR_JAMMED
#define _cmd_State_ARRAYSIZE ((cmd_State)(cmd_State_ERROR_JAMMED+1))

#define cmd_RequestLockStateUpdate_desiredState_ENUMTYPE cmd_State



#define cmd_ConfirmLockStateUpdate_desiredState_ENUMTYPE cmd_State
#define cmd_ConfirmLockStateUpdate_reportedState_ENUMTYPE cmd_State




/* Initializer values for message structs */
#define cmd_RequestLockStateUpdate_init_default  {false, _cmd_State_MIN, false, 0}
#define cmd_RequestLockStateGet_init_default     {false, cmd_RequestLockStateUpdate_init_default}
#define cmd_Request_init_default                 {false, cmd_RequestLockStateGet_init_default}
#define cmd_ConfirmLockStateUpdate_init_default  {false, _cmd_State_MIN, false, _cmd_State_MIN, false, 0}
#define cmd_ConfirmLockStateGet_init_default     {false, cmd_ConfirmLockStateUpdate_init_default}
#define cmd_Confirm_init_default                 {false, cmd_ConfirmLockStateGet_init_default}
#define cmd_RequestLockStateUpdate_init_zero     {false, _cmd_State_MIN, false, 0}
#define cmd_RequestLockStateGet_init_zero        {false, cmd_RequestLockStateUpdate_init_zero}
#define cmd_Request_init_zero                    {false, cmd_RequestLockStateGet_init_zero}
#define cmd_ConfirmLockStateUpdate_init_zero     {false, _cmd_State_MIN, false, _cmd_State_MIN, false, 0}
#define cmd_ConfirmLockStateGet_init_zero        {false, cmd_ConfirmLockStateUpdate_init_zero}
#define cmd_Confirm_init_zero                    {false, cmd_ConfirmLockStateGet_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define cmd_RequestLockStateUpdate_desiredState_tag 1
#define cmd_RequestLockStateUpdate_desiredStateToken_tag 2
#define cmd_RequestLockStateGet_request_tag      2
#define cmd_Request_lockStateUpdate_tag          1
#define cmd_ConfirmLockStateUpdate_desiredState_tag 1
#define cmd_ConfirmLockStateUpdate_reportedState_tag 2
#define cmd_ConfirmLockStateUpdate_desiredStateToken_tag 3
#define cmd_ConfirmLockStateGet_confirm_tag      2
#define cmd_Confirm_lockStateConfirm_tag         2

/* Struct field encoding specification for nanopb */
#define cmd_RequestLockStateUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    desiredState,      1) \
X(a, STATIC,   OPTIONAL, UINT64,   desiredStateToken,   2)
#define cmd_RequestLockStateUpdate_CALLBACK NULL
#define cmd_RequestLockStateUpdate_DEFAULT NULL

#define cmd_RequestLockStateGet_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  request,           2)
#define cmd_RequestLockStateGet_CALLBACK NULL
#define cmd_RequestLockStateGet_DEFAULT NULL
#define cmd_RequestLockStateGet_request_MSGTYPE cmd_RequestLockStateUpdate

#define cmd_Request_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lockStateUpdate,   1)
#define cmd_Request_CALLBACK NULL
#define cmd_Request_DEFAULT NULL
#define cmd_Request_lockStateUpdate_MSGTYPE cmd_RequestLockStateGet

#define cmd_ConfirmLockStateUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    desiredState,      1) \
X(a, STATIC,   OPTIONAL, UENUM,    reportedState,     2) \
X(a, STATIC,   OPTIONAL, UINT64,   desiredStateToken,   3)
#define cmd_ConfirmLockStateUpdate_CALLBACK NULL
#define cmd_ConfirmLockStateUpdate_DEFAULT NULL

#define cmd_ConfirmLockStateGet_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  confirm,           2)
#define cmd_ConfirmLockStateGet_CALLBACK NULL
#define cmd_ConfirmLockStateGet_DEFAULT NULL
#define cmd_ConfirmLockStateGet_confirm_MSGTYPE cmd_ConfirmLockStateUpdate

#define cmd_Confirm_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lockStateConfirm,   2)
#define cmd_Confirm_CALLBACK NULL
#define cmd_Confirm_DEFAULT NULL
#define cmd_Confirm_lockStateConfirm_MSGTYPE cmd_ConfirmLockStateGet

extern const pb_msgdesc_t cmd_RequestLockStateUpdate_msg;
extern const pb_msgdesc_t cmd_RequestLockStateGet_msg;
extern const pb_msgdesc_t cmd_Request_msg;
extern const pb_msgdesc_t cmd_ConfirmLockStateUpdate_msg;
extern const pb_msgdesc_t cmd_ConfirmLockStateGet_msg;
extern const pb_msgdesc_t cmd_Confirm_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cmd_RequestLockStateUpdate_fields &cmd_RequestLockStateUpdate_msg
#define cmd_RequestLockStateGet_fields &cmd_RequestLockStateGet_msg
#define cmd_Request_fields &cmd_Request_msg
#define cmd_ConfirmLockStateUpdate_fields &cmd_ConfirmLockStateUpdate_msg
#define cmd_ConfirmLockStateGet_fields &cmd_ConfirmLockStateGet_msg
#define cmd_Confirm_fields &cmd_Confirm_msg

/* Maximum encoded size of messages (where known) */
#define CMD_SRC_PROTO_CMD_PB_H_MAX_SIZE          cmd_Confirm_size
#define cmd_ConfirmLockStateGet_size             17
#define cmd_ConfirmLockStateUpdate_size          15
#define cmd_Confirm_size                         19
#define cmd_RequestLockStateGet_size             15
#define cmd_RequestLockStateUpdate_size          13
#define cmd_Request_size                         17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
